Update junit and add javax dependencies
Add javax dependency back in as it's being used by a package
pulled in from magistrates library

Update the junit dependency to fix the below error after updating
the spring boot version:

java.lang.NoClassDefFoundError: org/junit/jupiter/api/io/TempDirFactory